name: App Log Monitoring

on:
    schedule:
        - cron: '*/5 * * * *'  # Run every 5 minutes

jobs:
    monitor_logs:
        runs-on: ubuntu-latest
        
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Install doctl
              uses: digitalocean/action-doctl@v2
              with:
                  token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

            - name: Retrieve app logs
              id: get_logs
              run: |
                  logs=$(doctl apps logs ${{ secrets.DIGITALOCEAN_APP_ID }})
                  echo "::set-output name=logs::$logs"
                  
            - name: Check for errors
              id: check_errors
              if: contains(steps.get_logs.outputs.logs, 'error:') || contains(steps.get_logs.outputs.logs, 'fail:')
              env:
                  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  echo "Errors found in the app logs:"
                  echo "${{ steps.get_logs.outputs.logs }}"
                  echo "Disabling the workflow to prevent further notifications."
                  gh workflow disable "App Log Monitoring"

            - name: Fail the workflow
              if: contains(steps.get_logs.outputs.logs, 'error:')
              run: exit 1
