name: Build and test

on:
    push:
        branches:
            - '*'
        tags-ignore:
            - 'v*'
        paths-ignore:
            - 'todo.txt'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
    
    - name: Build
      run: dotnet build --configuration Release

    - name: Test
      run: dotnet test /p:CollectCoverage=true --filter "Category!=Integration&Category!=Database"
